name: CI

on:
  push:

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: clang-14
            make: test
            info: 'clang-14 + test'

    name: '${{ matrix.os }}: ${{ matrix.info }}'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make cmake clang libgtest-dev

      - name: Build and test project
        run: |
          make ${{ matrix.make }}

      - name: Clean build artifacts
        if: always()
        run: |
          make clean
